### PR TITLE
Add verbosity level

### PR DESCRIPTION
**Pull request by skaspi**
Update the stages of v2v flow

### CODE REVIEW

**Review by KKoukiou — COMMENTED** [review]
The second commit in merge commit, I think you added it by mistake.
The first has more changes than what the commit message says.

**Review by kobihk — APPROVED** [review]

**Comment by KKoukiou** [comment]
@kobihk @skaspi This PR was wrong and should not have been merged as is.

There were unrelated changes, commit messages were wrong, and there was also a merge commit.

**Comment by kobihk** [comment]
@KKoukiou you right!! 
I looked at the "File Changed" and missed it. 
Do you think it's better to revert and create new PR?

**Comment by KKoukiou** [comment]
> @KKoukiou you right!!
> I looked at the "File Changed" and missed it.
> Do you think it's better to revert and create new PR?

I guess let's be more careful in the future.
Revert will just create a revert commit, it will mess up with history even more. (You can force push removing the two commits, and create a new PR if you have direct push permissions)

**Pull request merged**
